# ============================================================
# modules/cognito/main.tf
#
# Cognito User Pool module for ActivaClub.
#
# Creates:
#   - User Pool with email-based sign-in and strong password policy
#   - Custom attribute custom:dni (passed at SignUp, used post-confirmation)
#   - App Client (no secret, SRP + password + admin auth flows)
#   - Cognito-hosted domain for the OAuth2 / hosted UI endpoints
#   - Three groups: Admin, Manager, Member
#
# Design decisions (Rev 2 — AC-001 + AC-002):
#   - allow_admin_create_user_only = false so the backend Lambda can call
#     SignUp (native Cognito flow) which triggers OTP email verification
#   - MFA = ON (required) using Email OTP only — no TOTP for MVP
#   - prevent_user_existence_errors = ENABLED prevents user enumeration on login
#   - No client secret — the frontend is a SPA and cannot store secrets
#
# Requires AWS provider >= 5.60 for email_mfa_configuration block support.
# ============================================================

# ------------------------------------------------------------
# Recreation trigger
# Changing force_recreate_token forces destroy + recreate of the
# User Pool — needed when new schema attributes are added, since
# Cognito does not allow modifying schema in-place via UpdateUserPool.
# ------------------------------------------------------------
resource "terraform_data" "cognito_recreate_trigger" {
  input = var.force_recreate_token
}

# ------------------------------------------------------------
# User Pool
# ------------------------------------------------------------
resource "aws_cognito_user_pool" "this" {
  name = "${var.project}-${var.env}"

  # Users sign in with their email address
  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]

  # Allow SignUp API so the backend Lambda can call it directly.
  # The Lambda validates the DNI against SeedMembersTable before calling
  # SignUp — it acts as the sole gatekeeper; the frontend never calls
  # Cognito APIs directly for registration.
  admin_create_user_config {
    allow_admin_create_user_only = false
  }

  # Strong password policy
  password_policy {
    minimum_length                   = 8
    require_uppercase                = true
    require_lowercase                = true
    require_numbers                  = true
    require_symbols                  = true
    temporary_password_validity_days = 7
  }

  # Email MFA required for all users (AC-002).
  # TOTP is disabled — email OTP is the sole second factor for MVP.
  mfa_configuration = "ON"

  software_token_mfa_configuration {
    enabled = false
  }

  # Email MFA OTP message template.
  # {####} is replaced by the 6-digit code generated by Cognito.
  email_mfa_configuration {
    message = var.email_mfa_message
  }

  # Account recovery — email is primary.
  # AWS requires at least two recovery mechanisms when Email MFA is enabled;
  # verified_email alone is rejected with InvalidParameterException.
  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }
    recovery_mechanism {
      name     = "verified_phone_number"
      priority = 2
    }
  }

  # SES email sender — required for Email MFA (COGNITO_DEFAULT does not support
  # EmailMfaConfiguration). The identity must be verified in SES before apply.
  email_configuration {
    email_sending_account = "DEVELOPER"
    from_email_address    = "ActivaClub <${var.ses_from_email}>"
    source_arn            = var.ses_source_arn
  }

  # Email verification message
  verification_message_template {
    default_email_option = "CONFIRM_WITH_CODE"
  }

  # Standard email attribute
  schema {
    name                = "email"
    attribute_data_type = "String"
    required            = true
    mutable             = true

    string_attribute_constraints {
      min_length = 5
      max_length = 254
    }
  }

  # Custom DNI attribute (AC-001).
  # Passed at SignUp by the backend Lambda; read via AdminGetUser after
  # ConfirmSignUp to look up the member's membership_type in SeedMembersTable.
  # Immutable — prevents post-registration tampering.
  schema {
    name                     = "dni"
    attribute_data_type      = "String"
    required                 = false
    mutable                  = false
    developer_only_attribute = false

    string_attribute_constraints {
      min_length = 7
      max_length = 8
    }
  }

  # Device tracking disabled (AC-010).
  # Session persistence uses a plain refresh token stored in localStorage — no
  # Cognito device tracking required. Enabling device tracking causes Cognito to
  # embed a device key in the refresh token; REFRESH_TOKEN_AUTH then requires that
  # key to be sent back, which fails with "Invalid Refresh Token." when omitted.
  device_configuration {
    challenge_required_on_new_device      = false
    device_only_remembered_on_user_prompt = false
  }

  # CustomEmailSender trigger — optional.
  # When lambda_arn is provided Cognito encrypts the OTP code with the KMS key
  # and invokes the Lambda instead of sending a plain-text email directly.
  dynamic "lambda_config" {
    for_each = var.custom_email_sender_lambda_arn != "" ? [1] : []
    content {
      kms_key_id = var.custom_email_sender_kms_key_arn
      custom_email_sender {
        lambda_arn     = var.custom_email_sender_lambda_arn
        lambda_version = "V1_0"
      }
    }
  }

  tags = merge(var.tags, {
    Name        = "${var.project}-${var.env}"
    Environment = var.env
    ManagedBy   = "terraform"
  })

  lifecycle {
    replace_triggered_by = [terraform_data.cognito_recreate_trigger]
  }
}

# ------------------------------------------------------------
# App Client — used by the ActivaClub frontend (SPA)
# No client secret — SPAs cannot store secrets securely
# ------------------------------------------------------------
resource "aws_cognito_user_pool_client" "this" {
  name         = "${var.project}-app-client-${var.env}"
  user_pool_id = aws_cognito_user_pool.this.id

  # No secret — public client (SPA)
  generate_secret = false

  # Auth flows enabled:
  #   - ALLOW_USER_PASSWORD_AUTH       : direct username/password (used by AdminInitiateAuth)
  #   - ALLOW_ADMIN_USER_PASSWORD_AUTH : required for AdminInitiateAuth server-side flow (AC-002)
  #   - ALLOW_USER_SRP_AUTH            : Secure Remote Password (future hardening)
  #   - ALLOW_REFRESH_TOKEN_AUTH       : silent token refresh
  explicit_auth_flows = [
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_ADMIN_USER_PASSWORD_AUTH",
    "ALLOW_USER_SRP_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]

  # Token validity
  access_token_validity  = 1  # hours
  id_token_validity      = 1  # hours
  refresh_token_validity = 30 # days

  token_validity_units {
    access_token  = "hours"
    id_token      = "hours"
    refresh_token = "days"
  }

  # Hides whether a user exists during auth — prevents user enumeration
  prevent_user_existence_errors = "ENABLED"
}

# ------------------------------------------------------------
# Cognito-hosted domain
# Provides the /oauth2/token, /login, /logout endpoints.
# Domain name must be globally unique across all AWS accounts.
# ------------------------------------------------------------
resource "aws_cognito_user_pool_domain" "this" {
  domain       = "${var.project}-${var.env}"
  user_pool_id = aws_cognito_user_pool.this.id
}

# ------------------------------------------------------------
# User Groups
# Precedence determines which group's permissions apply when
# a user belongs to multiple groups (lower = higher priority).
# ------------------------------------------------------------

# Administrators — full club management access
resource "aws_cognito_user_group" "admin" {
  name         = "Admin"
  user_pool_id = aws_cognito_user_pool.this.id
  description  = "Club administrators with full management access"
  precedence   = 1
}

# Managers — day-to-day operations, cannot manage other admins
resource "aws_cognito_user_group" "manager" {
  name         = "Manager"
  user_pool_id = aws_cognito_user_pool.this.id
  description  = "Club managers responsible for day-to-day operations"
  precedence   = 2
}

# Members — regular club members, read-only on most resources
resource "aws_cognito_user_group" "member" {
  name         = "Member"
  user_pool_id = aws_cognito_user_pool.this.id
  description  = "Regular club members"
  precedence   = 3
}
